version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'mateusdb'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 's9cst0sf'
      MYSQL_ROOT_PASSWORD: 's9cst0sf'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db: